CREATE TABLE sharing_preference (
    user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    demographics BOOLEAN NOT NULL DEFAULT FALSE,
    allergies BOOLEAN NOT NULL DEFAULT FALSE,
    medications BOOLEAN NOT NULL DEFAULT FALSE,
    conditions BOOLEAN NOT NULL DEFAULT FALSE,
    emergency_contact BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
